<?php
/**
 * FingerprintsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Aternos\CurseForgeApi\ApiException;
use Aternos\CurseForgeApi\Configuration;
use Aternos\CurseForgeApi\HeaderSelector;
use Aternos\CurseForgeApi\ObjectSerializer;

/**
 * FingerprintsApi Class Doc Comment
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FingerprintsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getFingerprintFuzzyMatches' => [
            'application/json',
        ],
        'getFingerprintFuzzyMatchesByGame' => [
            'application/json',
        ],
        'getFingerprintMatches' => [
            'application/json',
        ],
        'getFingerprintMatchesByGame' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getFingerprintFuzzyMatches
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatches'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse
     */
    public function getFingerprintFuzzyMatches($get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatches'][0])
    {
        list($response) = $this->getFingerprintFuzzyMatchesWithHttpInfo($get_fuzzy_matches_request_body, $contentType);
        return $response;
    }

    /**
     * Operation getFingerprintFuzzyMatchesWithHttpInfo
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatches'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFingerprintFuzzyMatchesWithHttpInfo($get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatches'][0])
    {
        $request = $this->getFingerprintFuzzyMatchesRequest($get_fuzzy_matches_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFingerprintFuzzyMatchesAsync
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintFuzzyMatchesAsync($get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatches'][0])
    {
        return $this->getFingerprintFuzzyMatchesAsyncWithHttpInfo($get_fuzzy_matches_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFingerprintFuzzyMatchesAsyncWithHttpInfo
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintFuzzyMatchesAsyncWithHttpInfo($get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatches'][0])
    {
        $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse';
        $request = $this->getFingerprintFuzzyMatchesRequest($get_fuzzy_matches_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFingerprintFuzzyMatches'
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFingerprintFuzzyMatchesRequest($get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatches'][0])
    {

        // verify the required parameter 'get_fuzzy_matches_request_body' is set
        if ($get_fuzzy_matches_request_body === null || (is_array($get_fuzzy_matches_request_body) && count($get_fuzzy_matches_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_fuzzy_matches_request_body when calling getFingerprintFuzzyMatches'
            );
        }


        $resourcePath = '/v1/fingerprints/fuzzy';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_fuzzy_matches_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_fuzzy_matches_request_body));
            } else {
                $httpBody = $get_fuzzy_matches_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFingerprintFuzzyMatchesByGame
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatchesByGame'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse
     */
    public function getFingerprintFuzzyMatchesByGame($game_id, $get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatchesByGame'][0])
    {
        list($response) = $this->getFingerprintFuzzyMatchesByGameWithHttpInfo($game_id, $get_fuzzy_matches_request_body, $contentType);
        return $response;
    }

    /**
     * Operation getFingerprintFuzzyMatchesByGameWithHttpInfo
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatchesByGame'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFingerprintFuzzyMatchesByGameWithHttpInfo($game_id, $get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatchesByGame'][0])
    {
        $request = $this->getFingerprintFuzzyMatchesByGameRequest($game_id, $get_fuzzy_matches_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFingerprintFuzzyMatchesByGameAsync
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintFuzzyMatchesByGameAsync($game_id, $get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatchesByGame'][0])
    {
        return $this->getFingerprintFuzzyMatchesByGameAsyncWithHttpInfo($game_id, $get_fuzzy_matches_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFingerprintFuzzyMatchesByGameAsyncWithHttpInfo
     *
     * Get Fingerprints Fuzzy Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintFuzzyMatchesByGameAsyncWithHttpInfo($game_id, $get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatchesByGame'][0])
    {
        $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintFuzzyMatchesResponse';
        $request = $this->getFingerprintFuzzyMatchesByGameRequest($game_id, $get_fuzzy_matches_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFingerprintFuzzyMatchesByGame'
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFuzzyMatchesRequestBody $get_fuzzy_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintFuzzyMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFingerprintFuzzyMatchesByGameRequest($game_id, $get_fuzzy_matches_request_body, string $contentType = self::contentTypes['getFingerprintFuzzyMatchesByGame'][0])
    {

        // verify the required parameter 'game_id' is set
        if ($game_id === null || (is_array($game_id) && count($game_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $game_id when calling getFingerprintFuzzyMatchesByGame'
            );
        }

        // verify the required parameter 'get_fuzzy_matches_request_body' is set
        if ($get_fuzzy_matches_request_body === null || (is_array($get_fuzzy_matches_request_body) && count($get_fuzzy_matches_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_fuzzy_matches_request_body when calling getFingerprintFuzzyMatchesByGame'
            );
        }


        $resourcePath = '/v1/fingerprints/fuzzy/{gameId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($game_id !== null) {
            $resourcePath = str_replace(
                '{' . 'gameId' . '}',
                ObjectSerializer::toPathValue($game_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_fuzzy_matches_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_fuzzy_matches_request_body));
            } else {
                $httpBody = $get_fuzzy_matches_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFingerprintMatches
     *
     * Get Fingerprints Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatches'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse
     */
    public function getFingerprintMatches($get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatches'][0])
    {
        list($response) = $this->getFingerprintMatchesWithHttpInfo($get_fingerprint_matches_request_body, $contentType);
        return $response;
    }

    /**
     * Operation getFingerprintMatchesWithHttpInfo
     *
     * Get Fingerprints Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatches'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFingerprintMatchesWithHttpInfo($get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatches'][0])
    {
        $request = $this->getFingerprintMatchesRequest($get_fingerprint_matches_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFingerprintMatchesAsync
     *
     * Get Fingerprints Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintMatchesAsync($get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatches'][0])
    {
        return $this->getFingerprintMatchesAsyncWithHttpInfo($get_fingerprint_matches_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFingerprintMatchesAsyncWithHttpInfo
     *
     * Get Fingerprints Matches
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintMatchesAsyncWithHttpInfo($get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatches'][0])
    {
        $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse';
        $request = $this->getFingerprintMatchesRequest($get_fingerprint_matches_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFingerprintMatches'
     *
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatches'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFingerprintMatchesRequest($get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatches'][0])
    {

        // verify the required parameter 'get_fingerprint_matches_request_body' is set
        if ($get_fingerprint_matches_request_body === null || (is_array($get_fingerprint_matches_request_body) && count($get_fingerprint_matches_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_fingerprint_matches_request_body when calling getFingerprintMatches'
            );
        }


        $resourcePath = '/v1/fingerprints';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_fingerprint_matches_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_fingerprint_matches_request_body));
            } else {
                $httpBody = $get_fingerprint_matches_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getFingerprintMatchesByGame
     *
     * Get Fingerprints Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatchesByGame'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse
     */
    public function getFingerprintMatchesByGame($game_id, $get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatchesByGame'][0])
    {
        list($response) = $this->getFingerprintMatchesByGameWithHttpInfo($game_id, $get_fingerprint_matches_request_body, $contentType);
        return $response;
    }

    /**
     * Operation getFingerprintMatchesByGameWithHttpInfo
     *
     * Get Fingerprints Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatchesByGame'] to see the possible values for this operation
     *
     * @throws \Aternos\CurseForgeApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getFingerprintMatchesByGameWithHttpInfo($game_id, $get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatchesByGame'][0])
    {
        $request = $this->getFingerprintMatchesByGameRequest($game_id, $get_fingerprint_matches_request_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getFingerprintMatchesByGameAsync
     *
     * Get Fingerprints Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintMatchesByGameAsync($game_id, $get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatchesByGame'][0])
    {
        return $this->getFingerprintMatchesByGameAsyncWithHttpInfo($game_id, $get_fingerprint_matches_request_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getFingerprintMatchesByGameAsyncWithHttpInfo
     *
     * Get Fingerprints Matches
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getFingerprintMatchesByGameAsyncWithHttpInfo($game_id, $get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatchesByGame'][0])
    {
        $returnType = '\Aternos\CurseForgeApi\Model\GetFingerprintMatchesResponse';
        $request = $this->getFingerprintMatchesByGameRequest($game_id, $get_fingerprint_matches_request_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getFingerprintMatchesByGame'
     *
     * @param  int $game_id The game id the find matches in (required)
     * @param  \Aternos\CurseForgeApi\Model\GetFingerprintMatchesRequestBody $get_fingerprint_matches_request_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getFingerprintMatchesByGame'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getFingerprintMatchesByGameRequest($game_id, $get_fingerprint_matches_request_body, string $contentType = self::contentTypes['getFingerprintMatchesByGame'][0])
    {

        // verify the required parameter 'game_id' is set
        if ($game_id === null || (is_array($game_id) && count($game_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $game_id when calling getFingerprintMatchesByGame'
            );
        }

        // verify the required parameter 'get_fingerprint_matches_request_body' is set
        if ($get_fingerprint_matches_request_body === null || (is_array($get_fingerprint_matches_request_body) && count($get_fingerprint_matches_request_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_fingerprint_matches_request_body when calling getFingerprintMatchesByGame'
            );
        }


        $resourcePath = '/v1/fingerprints/{gameId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($game_id !== null) {
            $resourcePath = str_replace(
                '{' . 'gameId' . '}',
                ObjectSerializer::toPathValue($game_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_fingerprint_matches_request_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_fingerprint_matches_request_body));
            } else {
                $httpBody = $get_fingerprint_matches_request_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
