<?php
/**
 * FilesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Api;

use \Aternos\CurseForgeApi\Configuration;
use \Aternos\CurseForgeApi\ApiException;
use \Aternos\CurseForgeApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FilesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getFiles
     *
     * Get files.
     *
     */
    public function testGetFiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getModFile
     *
     * Get mod file..
     *
     */
    public function testGetModFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getModFileChangelog
     *
     * Get mod file changelog.
     *
     */
    public function testGetModFileChangelog()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getModFileDownloadURL
     *
     * Get Mod File Download URL.
     *
     */
    public function testGetModFileDownloadURL()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getModFiles
     *
     * Get mod files..
     *
     */
    public function testGetModFiles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
