<?php
/**
 * MinecraftApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Api;

use \Aternos\CurseForgeApi\Configuration;
use \Aternos\CurseForgeApi\ApiException;
use \Aternos\CurseForgeApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MinecraftApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MinecraftApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMinecraftModLoaders
     *
     * Get Minecraft ModLoaders.
     *
     */
    public function testGetMinecraftModLoaders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMinecraftVersions
     *
     * Get Minecraft Versions.
     *
     */
    public function testGetMinecraftVersions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSpecificMinecraftModLoader
     *
     * Get Specific Minecraft ModLoader.
     *
     */
    public function testGetSpecificMinecraftModLoader()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSpecificMinecraftVersion
     *
     * Get Specific Minecraft Version.
     *
     */
    public function testGetSpecificMinecraftVersion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
