<?php
/**
 * ModsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Api;

use \Aternos\CurseForgeApi\Configuration;
use \Aternos\CurseForgeApi\ApiException;
use \Aternos\CurseForgeApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ModsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ModsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getFeaturedMods
     *
     * Get featured mods..
     *
     */
    public function testGetFeaturedMods()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMod
     *
     * Get a single mod..
     *
     */
    public function testGetMod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getModDescription
     *
     * Get mod description..
     *
     */
    public function testGetModDescription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMods
     *
     * Get a list of mods..
     *
     */
    public function testGetMods()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for searchMods
     *
     * Get all mods that match the search criteria..
     *
     */
    public function testSearchMods()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
