<?php
/**
 * FileRelationType
 *
 * PHP version 8.1
 *
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Model;

/**
 * FileRelationType Class Doc Comment
 *
 * @description Possible enum values:  * 1 &#x3D; EmbeddedLibrary  * 2 &#x3D; OptionalDependency  * 3 &#x3D; RequiredDependency  * 4 &#x3D; Tool  * 5 &#x3D; Incompatible  * 6 &#x3D; Include
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum FileRelationType: int
{
    case EMBEDDED_LIBRARY = 1;

    case OPTIONAL_DEPENDENCY = 2;

    case REQUIRED_DEPENDENCY = 3;

    case TOOL = 4;

    case INCOMPATIBLE = 5;

    case _INCLUDE = 6;
}


