<?php
/**
 * GameVersionStatus
 *
 * PHP version 8.1
 *
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Model;

/**
 * GameVersionStatus Class Doc Comment
 *
 * @description Possible enum values:  * 1 &#x3D; Approved  * 2 &#x3D; Deleted  * 3 &#x3D; New
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum GameVersionStatus: int
{
    case APPROVED = 1;

    case DELETED = 2;

    case _NEW = 3;
}


