<?php
/**
 * ModStatus
 *
 * PHP version 8.1
 *
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Model;

/**
 * ModStatus Class Doc Comment
 *
 * @description Current mod status Possible enum values:  * 1 &#x3D; New  * 2 &#x3D; ChangesRequired  * 3 &#x3D; UnderSoftReview  * 4 &#x3D; Approved  * 5 &#x3D; Rejected  * 6 &#x3D; ChangesMade  * 7 &#x3D; Inactive  * 8 &#x3D; Abandoned  * 9 &#x3D; Deleted  * 10 &#x3D; UnderReview
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ModStatus: int
{
    case _NEW = 1;

    case CHANGES_REQUIRED = 2;

    case UNDER_SOFT_REVIEW = 3;

    case APPROVED = 4;

    case REJECTED = 5;

    case CHANGES_MADE = 6;

    case INACTIVE = 7;

    case ABANDONED = 8;

    case DELETED = 9;

    case UNDER_REVIEW = 10;
}


