<?php
/**
 * PlatformType
 *
 * PHP version 8.1
 *
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Model;

/**
 * PlatformType Class Doc Comment
 *
 * @description * 0 &#x3D; Empty * 1 &#x3D; Windows * 2 &#x3D; XboxOne * 3 &#x3D; XboxXS * 4 &#x3D; Linux * 5 &#x3D; PS4 * 6 &#x3D; PS5 * 7 &#x3D; Mac * 8 &#x3D; IOS * 9 &#x3D; TVOS * 10 &#x3D; Android * 11 &#x3D; Switch * 12 &#x3D; WindowsServer * 13 &#x3D; LinuxServer
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum PlatformType: int
{
    case _EMPTY = 0;

    case WINDOWS = 1;

    case XBOX_ONE = 2;

    case XBOX_XS = 3;

    case LINUX = 4;

    case PS4 = 5;

    case PS5 = 6;

    case MAC = 7;

    case IOS = 8;

    case TVOS = 9;

    case ANDROID = 10;

    case _SWITCH = 11;

    case WINDOWS_SERVER = 12;

    case LINUX_SERVER = 13;
}


