<?php
/**
 * RatingScore
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aternos\CurseForgeApi\Model;
use \Aternos\CurseForgeApi\ObjectSerializer;

/**
 * RatingScore Class Doc Comment
 *
 * @category Class
 * @description * 0 &#x3D; NotEnoughReviews * 1 &#x3D; OverwhelminglyPositive * 2 &#x3D; VeryPositive * 3 &#x3D; Positive * 4 &#x3D; MostlyPositive * 5 &#x3D; Mixed * 6 &#x3D; MostlyNegative * 7 &#x3D; Negative * 8 &#x3D; VeryNegative * 9 &#x3D; OverwhelminglyNegative
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RatingScore
{
    /**
     * Possible values of this enum
     */
    public const NOT_ENOUGH_REVIEWS = 0;

    public const OVERWHELMINGLY_POSITIVE = 1;

    public const VERY_POSITIVE = 2;

    public const POSITIVE = 3;

    public const MOSTLY_POSITIVE = 4;

    public const MIXED = 5;

    public const MOSTLY_NEGATIVE = 6;

    public const NEGATIVE = 7;

    public const VERY_NEGATIVE = 8;

    public const OVERWHELMINGLY_NEGATIVE = 9;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_ENOUGH_REVIEWS,
            self::OVERWHELMINGLY_POSITIVE,
            self::VERY_POSITIVE,
            self::POSITIVE,
            self::MOSTLY_POSITIVE,
            self::MIXED,
            self::MOSTLY_NEGATIVE,
            self::NEGATIVE,
            self::VERY_NEGATIVE,
            self::OVERWHELMINGLY_NEGATIVE
        ];
    }
}


