<?php
/**
 * FingerprintMatchesResultTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Model;

use PHPUnit\Framework\TestCase;

/**
 * FingerprintMatchesResultTest Class Doc Comment
 *
 * @category    Class
 * @description FingerprintMatchesResult
 * @package     Aternos\CurseForgeApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FingerprintMatchesResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FingerprintMatchesResult"
     */
    public function testFingerprintMatchesResult()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_cache_built"
     */
    public function testPropertyIsCacheBuilt()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exact_matches"
     */
    public function testPropertyExactMatches()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exact_fingerprints"
     */
    public function testPropertyExactFingerprints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "partial_matches"
     */
    public function testPropertyPartialMatches()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "partial_match_fingerprints"
     */
    public function testPropertyPartialMatchFingerprints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "additional_properties"
     */
    public function testPropertyAdditionalProperties()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "installed_fingerprints"
     */
    public function testPropertyInstalledFingerprints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unmatched_fingerprints"
     */
    public function testPropertyUnmatchedFingerprints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
