<?php
/**
 * FolderFingerprintTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Model;

use PHPUnit\Framework\TestCase;

/**
 * FolderFingerprintTest Class Doc Comment
 *
 * @category    Class
 * @description FolderFingerprint
 * @package     Aternos\CurseForgeApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FolderFingerprintTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FolderFingerprint"
     */
    public function testFolderFingerprint()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "foldername"
     */
    public function testPropertyFoldername()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fingerprints"
     */
    public function testPropertyFingerprints()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
