<?php
/**
 * ModLoaderInstallMethodTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aternos\CurseForgeApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * CurseForge API
 *
 * HTTP API for CurseForge
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aternos\CurseForgeApi\Tests\Integration\Model;

use PHPUnit\Framework\TestCase;

/**
 * ModLoaderInstallMethodTest Class Doc Comment
 *
 * @category    Class
 * @description ModLoaderInstallMethod Possible enum values:  * 1 &#x3D; ForgeInstaller  * 2 &#x3D; ForgeJarInstall  * 3 &#x3D; ForgeInstaller_v2
 * @package     Aternos\CurseForgeApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ModLoaderInstallMethodTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ModLoaderInstallMethod"
     */
    public function testModLoaderInstallMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
